#include <iostream>
using namespace std;
main()
{
int num1;
int num2;
int num3;
int num4;
int num5;
int num6;
int num7;
int num8;
int num9;
int num10;
int num11;
int num12;
int num13;
int num14;
int num15;
int value;
int value2;
int value3;
int total;
cout << " enter num1: ";
cin >> num1;
cout << "enter num2: ";
cin >> num2;
cout << "enter num3: ";
cin >> num3;
cout << "enter num4: ";
cin >> num4;
cout << " enter num5: ";
cin >> num5;
cout << " enter num6: ";
cin >> num6;
cout << " enter num7: ";
cin >> num7;
cout << " enter num8: ";
cin >> num8;
cout << " enter num9: ";
cin >> num9;
cout << " enter num10: ";
cin >> num10;
cout << " enter num11: ";
cin >> num11;
cout << " enter num12: ";
cin >> num12;
cout << " enter num13: ";
cin >> num13;
cout << " enter num14: ";
cin >> num14;
cout << " enter num14: ";
cin >> num15;
value=num1+num2+num3+num4+num5;
value2=num6*num7*num8*num9*num10;
value3=num11-num12-num13-num14-num15;
total=(value+value2)-value3;
cout <<  "total is : " << total;
}

